name: Check for updates
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 1 * *' # Run once a month
jobs:
  flatpak-external-data-checker:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'flathub'
    strategy:
      matrix:
        branch: [ master ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: Flatpak External Data Checker
          GIT_COMMITTER_NAME: Flatpak External Data Checker
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --update --never-fork com.github.rafostar.Clapper.json
